### PR TITLE
FEATURE: display tags icon in post body

### PR DESCRIPTION
**Pull request by Lhcfl**
This commit allows displaying tags icon in the body of the post.

## Screenshots

New setting:

image

Before change:

image

After change:

image

Related meta topic: https://meta.discourse.org/t/tag-icons-dont-show-up-in-post-text/315852

### CODE REVIEW

**Comment by Lhcfl** [comment]
I'm not sure, but the meaning of this api is ["Register a custom prefix for a sidebar tag section link."](https://github.com/discourse/discourse/blob/main/app/assets/javascripts/discourse/app/lib/plugin-api.gjs#L2589) :thinking:

If we really want to do this, we should probably introduce a new api `replaceCookedTagRender`

**Comment by ZogStriP** [comment]
> I'm not sure, but the meaning of this api is ["Register a custom prefix for a sidebar tag section link."](https://github.com/discourse/discourse/blob/main/app/assets/javascripts/discourse/app/lib/plugin-api.gjs#L2589) 🤔

If it's for the sidebar, does it make sense to apply the icon in the `post` content as well? 🤔

**Comment by Lhcfl** [comment]
We actually have three different render systems here, responsible for the sidebar, tags on topic-list, and tags on post content

So maybe we should add a new api  :thinking:

**Comment by Lhcfl** [comment]
@ZogStriP How about this?  I rewrote it using `api.registerHashtagType`

**Review by ZogStriP — APPROVED** [review]
Niiice 🤩

**Comment by ZogStriP** [comment]
TBH, not even sure we need to have a setting for this. 

Having the custom icon show everywhere is a better and more consistent UX 👍

**Comment by Lhcfl** [comment]
Ok I removed it 🙂

**Pull request merged**
